### ISSUE TITLE
Exec auth wrongly assumes cert data to be base64 encoded

### ISSUE THREAD

**Issue by mruoss** [mruoss/kubereq#33]
Discovered here: https://github.com/livebook-dev/livebook/issues/2814

The API spec for `client.authentication.k8s.io/v1` states that the `clientCertificateData` and `clientKeyData` fields of the [`ExecCredentialStatus`](https://kubernetes.io/docs/reference/config-api/client-authentication.v1/#client-authentication-k8s-io-v1-ExecCredentialStatus) resources are PEM formatted. But there's no word about them being base64 encoded.

Kubereq wrongly assumes base64 encoding and fails to extract the information returned by the exec'ed command.

**Comment by mruoss** [comment]
@enewbury

Would you be willing to test this fix for your setup? You can just basically paste this in a Livebook and see if it works.

```ex
Mix.install([:kubereq])


kubeconfig = Kubereq.Kubeconfig.load(Kubereq.Kubeconfig.Default)
req = Kubereq.new(kubeconfig, "api/v1/namespaces/:namespace/configmaps/:name")
{:ok, %Req.Response{status: 200}} = Kubereq.list(req, "default")
```

**Comment by enewbury** [comment]
That works! thanks for the quick turnaround!
