### ISSUE TITLE
Delete request does not include name in the path

### ISSUE THREAD

**Issue by jonatanklosko** [mruoss/kubereq#41]
I've just noticed that removing a PVC actually removes all PVC in the same namespace. I think the reason is that the URL doesn't include name, so it's a batch delete:

https://github.com/mruoss/kubereq/blob/3caf5728dc164d50b1198b521306228ae649505a/lib/kubereq/step/operation.ex#L72

**Comment by mruoss** [comment]
Oof... big ooooops! I recall notice and fixing this... but... this stripping should actually be on the :delete_all funciton. I'll fix asap.

**Comment by mruoss** [comment]
Just remembered. Fixed on a branch I didn't think would take so long to finish... 
https://github.com/mruoss/kubereq/pull/37/files#diff-d5076506e5cc95b8453c90eb47671444dce56e8ed79ce5503e22b9a6e47c87ca

I will fix and release asap.

**Comment by jonatanklosko** [comment]
Thank you!

**Comment by mruoss** [comment]
@jonatanklosko Shall I provide a PR for updating livebook or are you going to do it?

**Comment by jonatanklosko** [comment]
@mruoss already updated, thanks :)
